services:
  ChatApp:
    image: openaichatapp
    build:
      context: .
      dockerfile: ./WebApp.Dockerfile
    environment:
      AZURE_OPENAI_RESOURCE: ${AZURE_OPENAI_RESOURCE}
      AZURE_OPENAI_MODEL: ${AZURE_OPENAI_MODEL}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
    ports:
      - 80:80
